# https://hub.docker.com/_/centos
FROM centos:centos7
LABEL org.opencontainers.image.authors="githubfoam"


RUN yum update -yq && \
    yum install epel-release -yq && \
    yum install ansible -yq

WORKDIR /tmp